project:
  type: website
  output-dir: docs

website:
  title: "Sam Lokanc"
  navbar:
    left:
      - href: pages/index.qmd
        text: Home
      - href: pages/about.qmd
        text: About
      - href: pages/projects.qmd
        text: Projects
      - href: pages/resume.qmd
        text: Resume

format:
  html:
    theme:
      light:
        - flatly
        - styles/custom-light.scss
      dark:
        - flatly
        - styles/custom-dark.scss



