project:
  type: website
  output-dir: docs

website:
  title: "Sam Lokanc"
  site-url: https://samlokanc.github.io/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: pdfs/resume.pdf
        text: Resume

format:
  html:
    include-in-header:
      - text: |
          <meta name="color-scheme" content="dark light">
          <script>
            document.documentElement.style.visibility = 'hidden';
            window.addEventListener('load', () => {
              document.documentElement.style.visibility = 'visible';
            });
          </script>
    css: styles/styles.css
    theme:
      light:
        - flatly
        - styles/custom-light.scss
      dark:
        - darkly
        - styles/custom-dark.scss
